### ISSUE TITLE
Create sign-in screen in Figma

### ISSUE THREAD

**Issue by rBergCode** [HikeMate/hikeMateApp#21]

**Comment by rBergCode** [comment]
These are the 2 proposed designs for the team
![Image](https://github.com/user-attachments/assets/53815d1b-3e8a-4a66-804d-84d861e73613)

**Comment by rBergCode** [comment]
Everyone agreed that the left (with the background image) design is better. [discussed on telegram]

**Comment by mchac15** [comment]
First off: I really like both designs given. 
The one on the left makes more sense in my opinion, but I feel like the button for signing in with Google looks a bit off in contrast with the colors in the picture. As discussed in Telegram, it isn't a good idea to make the background of the button blue since the Google logo has a blue shade, so I'd say that the button is best left like this for now until we find a potential solution after.

**Comment by rBergCode** [comment]
As everyone in the team agreed on the **left design**, I will select it for development.
As @mchac15 said, the button looks a bit weird for now but it will be **corrected later**.
