### ISSUE TITLE
Merge SignIn Composable with FirebaseAuth viewModel

### ISSUE THREAD

**Issue by rBergCode** [HikeMate/hikeMateApp#52]
This may be a little tricky bc of the way the authentication does not actually return anything but updates the state of the current user, so you'd have to implement it similarly to the bootcamp.

Done criteria:

- [x] clicking on the sign in actually triggers the sign in process
- [x] signing in successfully signs in the user and triggers the next step, so the navigation to the main menu

**Comment by Wylwi** [comment]
David took ownership of the task

**Comment by MaelImhof** [comment]
David is the BOSS for this task

**Comment by davidholzwarth** [comment]
@rBergCode thanks for taking over this task, at this point it is just the end to end tests which don't work yet. If you need any introduction to the code lmk:) There is PR #53 which is my try of implementing this code with the updated and fixed auth repository, I'm afraid Remy's implementation is outdated, since the auth repository changed since he had worked on this task.

**Comment by davidholzwarth** [comment]
@rBergCode I also just noticed that I have not connected the sign out button to the authViewModel yet.
