### ISSUE TITLE
Fix routes not showing correctly on the map

### ISSUE THREAD

**Issue by Wylwi** [HikeMate/hikeMateApp#74]
Routes sometimes short circuit points when rendered on the map. The issue might be backend (points are not in the correct order from the backend), or frontend (the points are not rendered in the correct order).

**Comment by MaelImhof** [comment]
**Discussion after the stand-up meeting**

Problem: OSM data is flawed in itself. Hikes are not composed of a single line each. They are divided into parts. The API we use returns a list of paths that are themselves composed of points. Each list of paths represents a hike. Paths are not necessarily connected to each other. They can even be completely disparate (see [this example](https://www.openstreetmap.org/relation/555139#map=11/46.1563/7.0683)).

How do we go about this problem?

For hikes such as the example above, it makes sense to simply discard them and not display them, neither on the map nor in the list. For this, the repository should try to link each route's paths into a single line. If it fails to do this (because of a threshold of how far away points can be from each other), it should discard the hike completely. This makes sense because it can be considered as corrupted data, and should hence not go to the view model.
